### ISSUE TITLE
Can't install extension

### ISSUE THREAD

**Issue by wilkens** [nikonratm/feedlybackgroundtabs#10]
I'm having trouble installing the extension on Safari 10.1.2 with MacOS 10.12.6. The not-very-helpful error message from Safari just says "Safari can't install this extension. An error occurred while installing this extension."

<img width="504" alt="feedly" src="https://user-images.githubusercontent.com/292487/29719578-abc551e6-8984-11e7-9891-75d644c7e89b.png">

I've tried uninstalling and reinstalling, and tried both the Apple extension gallery version and the GitHub version. Same result on two different machines, a MBP that's a year old and an iMac that's two years old. Any suggestions? Thanks!

**Comment by nikonratm** [comment]
Hmm, a bit of Googling reveals this from the 1Password site, maybe you can try these instructions and see how it goes?
https://support.1password.com/safari-cannot-install-extension/

**Comment by wilkens** [comment]
Thanks for this. No luck, alas; tried both a straight reinstall and deleting the extension from ~/Library/Safari/Extensions, but same error message result.

**Comment by nikonratm** [comment]
Since it works for me and other users I'm guessing its something specific to your setup. Here's the second result from Googling the error message... https://discussions.apple.com/thread/7501644?tstart=0

**Comment by wilkens** [comment]
OK, thanks. I'll work on it myself.
