### ISSUE TITLE
Broken by Safari 13?

### ISSUE THREAD

**Issue by Oakwine** [nikonratm/feedlybackgroundtabs#11]
Safari 13 seems to require all extensions to be part of the Mac App store. I tried to redownload this from your website, and I get the message "You can't open the application "FeedlyBackgroundTabs.app" because it may be damaged or incomplete." Also, the app icon is greyed out with a white slashed circle through it.

Safari 13.0, MacOS 10.14.6

**Comment by nikonratm** [comment]
Unfortunately Apple rejected the app to the Mac App Store because its functionality is too limited and I don't see a way around that for now. You should still be able to download and use it though since it is signed & verified for distribution. Are you using this link: https://raw.github.com/nikonratm/feedlybackgroundtabs/master/dist/FeedlyBackgroundTabs.app.zip ?

**Comment by Oakwine** [comment]
Ugh, Apple, that was the whole point of extensions! Little tweaks to make your life better!

I followed that link, unzipped the file, and I still get a broken app. I suspect that the installation of Safari 13 kills anything that calls itself an extension?

**Comment by nikonratm** [comment]
No, that link is the re-built Mac App, I'm running it on Safari 13 with that app right now...

**Comment by nikonratm** [comment]
Sometimes turning off auto-unzip in Safari helps?

Also: I agree re. Apple, frustrating that they forced me to change it and then just flat out rejected it... uhm

**Comment by Oakwine** [comment]
I had to right-click and "Show package contents". Now it works. Thank you for your assistance on this!

**Comment by nikonratm** [comment]
Great. Just to clarify, you had to show contents on the zip or the app or what? Perhaps the .app was getting renamed after unzipping?

**Comment by Oakwine** [comment]
I found the problem! The Unarchiver breaks the unzipping, but the built-in Archive Utility opens it correctly. Weird.

And THANK YOU for continuing to develop this extension/app. Feedly is useless without it.

**Comment by nikonratm** [comment]
Odd because I use Unarchiver too...

I'm going to keep trying to get Apple to accept the app, would definitely be the easiest way...

Thanks for your support!
