### ISSUE TITLE
Extension doesn't work w/ Safari 9.1.2

### ISSUE THREAD

**Issue by droussel** [nikonratm/feedlybackgroundtabs#4]
With Safari 9.1.2, the default shortcut 'v' doesn't open new tabs in the background and if trying another shortcut, it doesn't open the tab at all.

**Comment by nikonratm** [comment]
Hmm, droussel it's working just fine for me (see http://tinypic.com/m/jb0bxh/3 ). Are you saying you were using it until you updated Safari and it stopped working?

**Comment by thiloroe** [comment]
Same here. 'v' doesn't open in background anymore but in foreground, any other shortcut doesn't work at all. Stopped working a couple of days ago, when Feedly introduced a new layout.

**Comment by thiloroe** [comment]
'v' opens articles in background when I'm in "Full article view", other shortcuts don't do anything though. In "Magazine" and "Title only" view 'v' opens a foreground tab, other shortcuts don't work.

**Comment by nikonratm** [comment]
Aha. I've sorted out the issue. Unfortunately now that Apple requires a developer cert I can't publish an updated version just yet. As soon as its sorted I will update you guys and hopefully get it available in the extensions gallery once again.

In the meantime, feel free to support the cost of a developer license by donating here: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RD9TUVZFBUEWC

Thanks!

**Comment by nikonratm** [comment]
Hi guys, I've updated the extension and should be fixed. Let me know if otherwise.

**Comment by thiloroe** [comment]
Yes, works for me in magazine view. Thank you!
