### ISSUE TITLE
Extension doesn't work on Safari 10.0 Release 11 (Technology Preview)

### ISSUE THREAD

**Issue by tangestani** [nikonratm/feedlybackgroundtabs#5]
The extension doesn't seem to work on the latest Safari Technology Preview. It installs fine, but pressing 'v' opens tabs in the foreground. Is this version of Safari not supported yet?

**Comment by nikonratm** [comment]
Safari Technology preview is Apple's experimental browser so theres no telling whether this issue will ever make it into actual Safari. For now I won't be fixing this unless it becomes an issue in core Safari.

**Comment by tangestani** [comment]
It seems that the latest commit breaks functionality in core Safari too.

The problem is in `content.js`. It tries to get the `data-alternate-link` attribute from the `selectedEntry` element rather than the `u100Entry` element.

**Comment by nikonratm** [comment]
tangestani, extension v 1.3 is working for me in Safari 9.1.2 in all views in Feedly. Can you confirm you're using the newest version and if so how to reproduce this issue please.

**Comment by tangestani** [comment]
Just realized that my "core" Safari is version 10.0, since I had updated to macOS Sierra.
