### ISSUE TITLE
Stopped working after update

### ISSUE THREAD

**Issue by harleyjcooper** [nikonratm/feedlybackgroundtabs#8]
Now that I've updated to the latest version, the background tab button no longer has any effect.

**Comment by nikonratm** [comment]
Not sure which update you're referring to. Safari has been sitting at 10.0.1 for some time and the extension hasn't been updated by me for about 2 months. As far as I can tell, it's still working for myself and others. Please try un- / re-installing and if the issue persists please provide more info.

Thanks
